---
kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/drone-gotify

trigger:
  branch:
    - main
  event:
    - tag

steps:
  - name: test
    image: golang:1.22-alpine
    commands:
      - apk add --no-cache make
      - make test
    when:
      event:
        - push
        - pull_request

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: dipievil/drone-gotify 
      dockerfile: docker/Dockerfile
      tags:
        - latest
        - ${DRONE_TAG:-main}
    when:
      event:
        - push
        - tag
      branch:
        - main
        - master

---
kind: pipeline
type: docker
name: release-pipeline

steps:
  - name: release
    image: node:lts
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_PAT
      GITHUB_EMAIL:
        from_secret: GITHUB_EMAIL
      GITHUB_NAME:
        from_secret: GITHUB_NAME
    commands:
      - curl -fsSL https://bun.com/install | bash
      - export PATH="$HOME/.bun/bin:$PATH"
      - git config --global user.email "$GITHUB_EMAIL"
      - git config --global user.name "$GITHUB_NAME"
      - bun install
      - bunx semantic-release

trigger:
  branch:
    - main
  event:
    - push
